# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode_api', '0002_userprofile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(default=0)),
                ('solution_text', models.TextField(blank=True, null=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decode_api.Problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compiled', models.IntegerField(default=0)),
                ('total_solved', models.IntegerField(default=0)),
                ('cpp_solved', models.IntegerField(default=0)),
                ('python_solved', models.IntegerField(default=0)),
                ('c_solved', models.IntegerField(default=0)),
                ('java_solved', models.IntegerField(default=0)),
                ('other_solved', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
