# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_api', '0003_solution_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(default='')),
                ('language_id', models.CharField(max_length=2)),
                ('stdin', models.TextField(default='')),
                ('expected_output', models.TextField(default='')),
            ],
        ),
    ]
