# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_api', '0006_auto_20190307_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecode',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
